version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/frontend/  # ✅ 프론트엔드 전용 폴더로 변경

hooks:
  ApplicationStop:
    - location: frontend/scripts/stop_container.sh
      timeout: 300
      runas: ubuntu
  BeforeInstall:
    - location: frontend/scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu
    - location: frontend/scripts/set_env.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: frontend/scripts/start_container.sh
      timeout: 300
      runas: ubuntu
